export const configUploadStatus = "UPLOAD_STATUS"
export const configAddStatus = "ADD_STATUS"
export const addDepartmentList = "ADD_DEPARTMENT_LIST"
export const updateDepartmentList = "UPLOAD_DEPARTMENT_LIST"
export const setTokenKey = "SET_TOKEN"
export const setUsernameKey = "SET_USERNAME"